### PR TITLE
fix doc bugs

### PR DESCRIPTION
**Pull request by xinqiu**

### CODE REVIEW

**Comment by frnkvieira** [comment]
Already fixed in master branch. Thanks!

**Comment by xinqiu** [comment]
Maybe you forgot to fix it?

**Comment by frnkvieira** [comment]
@xinqiu It's fixed in master branch as I said, it's not released on Pypi yet if this is what you mean...thanks!

**Comment by xinqiu** [comment]
@frnkvieira I am sorry that I mean the doc bug.

**Comment by frnkvieira** [comment]
@xinqiu I was talking about the imports, didn't notice it, do you mind opening a pull request only with it? Thanks!

**Comment by xinqiu** [comment]
OK

**Pull request closed without merging**
